### PR TITLE
Consistency and Formatting

### PR DESCRIPTION
**Pull request by stphnwlsh**
Hi Mathias!

I saw you star and fork my code so I clicked on your profile and I'm a naturally curious person.  So I started to poke around your code.  I saw you were a student so I thought I'd give you a tip or too.  Feel free to reject this, all done for a bit of fun.

**Consistency is key** - your food API is well structured but you have some gaps around spacing and formatting so I took the liberty of adding an editor config file to the repo.  I used [Rahan Saeed's](https://github.com/RehanSaeed/EditorConfig) as I have found it helpful in the past.

If you want your code to be readable ensure consistent spacing throughout.  I like to group things like vars to allow the code to flow a little better.

Clean-up behind you, lots of unused usings here.  Quick and easy to clean-up.  Also lots of unused code there, I didn't touch it but you might want to remove it.  You don't need to keep it there just in case.  Git keeps your history so it's always available if you need it.

I can see you're working on a good Error handling process.  I've used this extension method to help me https://github.com/stphnwlsh/CleanMinimalApi/blob/9f563834611f494745dfbb17cc9564ff3b6209d0/src/Presentation/Extensions/ApplicationBuilderExtensions.cs.  However you could also look at https://www.youtube.com/watch?v=a1ye9eGTB98 from Nick Chapsas.  He talks about returning standard results rather than rethrowing errors.  

Anyways hope this help you.  Thanks for checking out my stuff!!!

Cheers

Steve

### CODE REVIEW

**Comment by stphnwlsh** [comment]
Oh also, as a professional, tests are your friend!!!  No one is asking for 100% test coverage but please write some tests to validate your functionality, it will help you in the long run

**Review by mnhnielsen — COMMENTED** [review]
Thanks for taking your time to go through the project. I am still very new to .Net - yes, I can see I have a lot of formatting 'mistakes' and unused stuff. This is still very much work in progress.

**Comment by stphnwlsh** [comment]
Mate I just want to make sure you took this the way I intended it. My intention was to give some guidance and help you out. 

Everyone starts out this way. Just wanted to show you how I approach code and that might help you build your own style.

Did not mean to offend you, and if I did. I'm sorry.

**Comment by mnhnielsen** [comment]
No no not at all. I very much appreciate your help. Sorry for not being clear - I appreciate all the help I can get :) Thanks

**Pull request merged**
